<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\HttpFoundation\Response;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder ->add('codeProduct')
            ->add('name')
            //\NumberFormatter::ROUND_HALFUP
            ->add('price')
            ->add('imageUrl',FileType::class)
            ->add('description',TextareaType::class)
        ->add('submit',SubmitType::class);



    }


}